### ISSUE TITLE
Error on lazy load

### ISSUE THREAD

**Issue by raducostea** [wags1999/angular-hmr-lazy-components#1]
I followed your instructions, i got HMR enabled but if i change a html file in a component from the lazy loaded module i get this

```
[WDS] App hot update...
log.js:24 [HMR] Checking for updates on the server...
log.js:24 [HMR] Updated modules:
log.js:24 [HMR]  - ./src/app/modules/dashboard/index/index.component.html
log.js:24 [HMR]  - ./src/app/modules/dashboard/index/index.component.ts
log.js:24 [HMR]  - ./src/app/modules/dashboard/dashboard.routing.ts
log.js:24 [HMR]  - ./src/app/modules/dashboard/dashboard.module.ts
log.js:24 [HMR] App is up to date.
core.js:15714 ERROR Error: Uncaught (in promise): Error: Type class_1 is part of the declarations of 2 modules: DashboardModule and DashboardModule! Please consider moving class_1 to a higher module that imports DashboardModule and DashboardModule. You can also create a new NgModule that exports and includes class_1 then import that NgModule in DashboardModule and DashboardModule.
Error: Type class_1 is part of the declarations of 2 modules: DashboardModule and DashboardModule! Please consider moving class_1 to a higher module that imports DashboardModule and DashboardModule. You can also create a new NgModule that exports and includes class_1 then import that NgModule in DashboardModule and DashboardModule.
```

```
Angular CLI: 7.3.3
Node: 8.12.0
OS: darwin x64
Angular: 7.2.6
```

Any idea what is going one? I can guess that it appends the module instead of reloading it.

I can see two modules getting created here
```
chunk {modules-dashboard-dashboard-module} modules-dashboard-dashboard-module.js, modules-dashboard-dashboard-module.90be0b060bcc42ec91b3.hot-update.js, modules-dashboard-dashboard-module.js.map, modules-dashboard-dashboard-module.90be0b060bcc42ec91b3.hot-update.js.map (modules-dashboard-dashboard-module) 1.22 MB  [rendered]
```

**Comment by wags1999** [comment]
This example was originally created on

- Angular CLI 7.0.2
- Node 10.15.0
- OS Windows x64
- Angular 7.0.1

I just updated to

- Angular CLI 7.3.8
- Angular 7.2.12

and everything still works.

In creating this example, I know I ran into that error several times when the components weren't being unloaded completely.  Are you able to set some breakpoints in the enableHmrRouterNgModule() method to confirm the addDisposeHandler() method is being run, and that the router.resetConfig() method is being run?

Otherwise, maybe the older version of Node might be to blame?  You could try updating that.

**Comment by jraadt** [comment]
I'm getting the same error. Seems to exist as soon as I have more than 1 route in my lazy feature module. The component for the route that I did not change causes the error.

With breakpoints I do see addDisposeHandler() method is being run and that the router.resetConfig() method is being run.

**Comment by wags1999** [comment]
@jraadt, thanks for troubleshooting that!  Yeah, guess I didn't try it with more than one component in the lazy route module.  As far as the code to add to the `enableHmrRouterNgModule()`, you can probably skip the call to the `dynamicComponentSvc`, since the lazy route components don't rely on it - so the key must be clearing the Angular compiler cache for those components.

Please commit your changes to the `enableHmrRouterNgModule()` method, and then submit a PR with your changes! :-)

**Comment by inovozenko** [comment]
Catch the same errors but related to Modules.

I have lazy loaded `DashboardModule`:

```javascript
@NgModule({
  imports: [
    CommonModule,

    ChartsModule,
    LayoutModule,
    ModalModule,

    dashboardRouting
  ],
  declarations: [
    ...
  ]
})
export class DashboardModule {
  constructor(moduleRef: NgModuleRef<DashboardModule>) {
    HmrModuleHelper.enableHmrRouterNgModule(module, moduleRef);
  }
}

HmrModuleHelper.enableHmrNodeModule(module);
```

And when I change component e.g. from `ChartsModule`, I get error that `LineChartComponent` `is part of the declarations of 2 modules: ChartsModule and ChartsModule!`

So, inside `enableHmrRouterNgModule` I do:

```javascript
          zone.run(() => {
            compiler.clearCache();

            //tell the router to reset its config - this causes it to purge the previously loaded module
            router.resetConfig(appRoutes);

            //tell the router to re-load the current route
            router.navigateByUrl(router.url);
          });
```

I clear all cache with `compiler.clearCache()`. And it is working and reloading entire `DashboardModule`.

It seems that current implementation of `HmrModuleHelper` requires this declaration in every modules (`ChartsModule` + `LayoutModule` + `ModalModule` in my example)  that used by lazy loaded module (`DashboardModule` in my example):

```javascript
export class DashboardModule {
  constructor(moduleRef: NgModuleRef<DashboardModule>) {
    HmrModuleHelper.enableHmrRouterNgModule(module, moduleRef);
  }
}

HmrModuleHelper.enableHmrNodeModule(module);
```

And personally I don't like this idea. So, I clear all cache of lazy loaded module.
